---
- name: Install Chaos Mesh on MicroK8s
  hosts: localhost
  become: yes
  tasks:
    - name: Add Chaos Mesh Helm repository
      shell: microk8s helm repo add chaos-mesh https://charts.chaos-mesh.org

    - name: Update Helm repositories
      shell: microk8s helm repo update

    - name: Install Chaos Mesh using Helm
      shell: >
        microk8s helm3 upgrade --install chaos-mesh chaos-mesh/chaos-mesh
        -n chaos-mesh
        --set chaosDaemon.runtime=containerd
        --set chaosDaemon.socketPath=/var/snap/microk8s/common/run/containerd.sock
        --version 2.7.1
        --create-namespace

    - name: Verify Chaos Mesh installation
      shell: microk8s kubectl get pods -n chaos-mesh
      register: chaos_status

    - name: Print Chaos Mesh status
      debug:
        msg: "{{ chaos_status.stdout_lines }}"
