info:
  version: 1.0.7
  description: SMF initial local configuration

configuration:
  smfName: SMF
  sbi:
    scheme: http
    registerIPv4: smf.free5gc.org
    bindingIPv4: smf.free5gc.org
    port: 8000
    tls:
      key: cert/smf.key
      pem: cert/smf.pem
  serviceNameList:
    - nsmf-pdusession
    - nsmf-event-exposure
    - nsmf-oam
  snssaiInfos:
    - sNssai:
        sst: 1
        sd: 010203
      dnnInfos:
        - dnn: internet
          dnaiList:
            - mec
          dns:
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
        - dnn: ims
          dns:
            ipv4: 8.8.8.8
        - dnn: enterprise
          dns:
            ipv4: 8.8.8.8
  plmnList:
    - mcc: 208
      mnc: 93
  locality: area1
  pfcp:
    nodeID: smf.free5gc.org
    listenAddr: smf.free5gc.org
    externalAddr: smf.free5gc.org
    heartbeatInterval: 5s
  userplaneInformation:
    upNodes:
      gNB1:
        type: AN
        nodeID: gnb.free5gc.org
      UPF1:
        type: UPF
        nodeID: upf1.free5gc.org
        sNssaiUpfInfos:
          - sNssai:
              sst: 1
              sd: 010203
            dnnUpfInfoList:
              - dnn: internet
                pools:
                  - cidr: 10.60.0.0/24
              - dnn: ims
                pools:
                  - cidr: 10.61.0.0/24
        interfaces:
          - interfaceType: N3
            endpoints:
              - upf1.free5gc.org
            networkInstances:
              - internet
              - ims
          - interfaceType: N9
            endpoints:
              - upf1.free5gc.org
            networkInstances:
              - internet
              - ims
      UPF2:
        type: UPF
        nodeID: upf2.free5gc.org
        sNssaiUpfInfos:
          - sNssai:
              sst: 1
              sd: 010203
            dnnUpfInfoList:
              - dnn: internet
                pools:
                  - cidr: 10.62.0.0/24
              - dnn: ims
                pools:
                  - cidr: 10.63.0.0/24
        interfaces:
          - interfaceType: N3
            endpoints:
              - upf2.free5gc.org
            networkInstances:
              - internet
              - ims
          - interfaceType: N9
            endpoints:
              - upf2.free5gc.org
            networkInstances:
              - internet
              - ims
      UPF3:
        type: UPF
        nodeID: upf3.free5gc.org
        sNssaiUpfInfos:
          - sNssai:
              sst: 1
              sd: 010203
            dnnUpfInfoList:
              - dnn: internet
                pools:
                  - cidr: 10.64.0.0/24
        interfaces:
          - interfaceType: N3
            endpoints:
              - upf3.free5gc.org
            networkInstances:
              - internet
      UPF4:
        type: UPF
        nodeID: upf4.free5gc.org
        sNssaiUpfInfos:
          - sNssai:
              sst: 1
              sd: 010203
            dnnUpfInfoList:
              - dnn: ims
                pools:
                  - cidr: 10.65.0.0/24
        interfaces:
          - interfaceType: N9
            endpoints:
              - upf4.free5gc.org
            networkInstances:
              - ims
      UPF5:
        type: UPF
        nodeID: upf5.free5gc.org
        sNssaiUpfInfos:
          - sNssai:
              sst: 1
              sd: 010203
            dnnUpfInfoList:
              - dnn: internet
                pools:
                  - cidr: 10.66.0.0/24
              - dnn: enterprise
                pools:
                  - cidr: 10.67.0.0/24
        interfaces:
          - interfaceType: N3
            endpoints:
              - upf5.free5gc.org
            networkInstances:
              - internet
              - enterprise
          - interfaceType: N9
            endpoints:
              - upf5.free5gc.org
            networkInstances:
              - internet
              - enterprise
    links:
      - A: gNB1
        B: UPF1
      - A: gNB1
        B: UPF2
      - A: gNB1
        B: UPF3
      - A: UPF1
        B: UPF4
      - A: gNB1
        B: UPF5
  t3591:
    enable: true
    expireTime: 16s
    maxRetryTimes: 3
  t3592:
    enable: true
    expireTime: 16s
    maxRetryTimes: 3
  nrfUri: http://nrf.free5gc.org:8000
  nrfCertPem: cert/nrf.pem
  urrPeriod: 10
  urrThreshold: 1000
  requestedUnit: 1000
  ulcl: true
logger:
  enable: true
  level: info
  reportCaller: false
