version: 1.0.3
description: UPF1 initial local configuration
pfcp:
  addr: upf1.free5gc.org
  nodeID: upf1.free5gc.org
  retransTimeout: 1s
  maxRetrans: 3
gtpu:
  forwarder: gtp5g
  ifList:
    - addr: upf1.free5gc.org
      type: N3
    - addr: upf1.free5gc.org
      type: N9
dnnList:
  - dnn: internet
    cidr: 10.60.0.0/24
  - dnn: ims
    cidr: 10.61.0.0/24
logger:
  enable: true
  level: info
  reportCaller: false
