version: 1.0.3
description: UPF3 initial local configuration
pfcp:
  addr: upf3.free5gc.org
  nodeID: upf3.free5gc.org
  retransTimeout: 1s
  maxRetrans: 3
gtpu:
  forwarder: gtp5g
  ifList:
    - addr: upf3.free5gc.org
      type: N3
dnnList:
  - dnn: internet
    cidr: 10.64.0.0/24
logger:
  enable: true
  level: info
  reportCaller: false
