amf:
  hostname: open5gs-amf-ngap
mcc: '999'
mnc: '70'
name: ueransim-gnb3
nodeSelector:
  role: ueransim
sd: '0x333333'
sst: 3
tac: '0003'
ues:
  apnList:
  - apn: internet
    emergency: false
    slice:
      sd: '0x333333'
      sst: 3
    type: IPv4
  count: 10
  enabled: true
  initialMSISDN: '0000000021'
  nodeSelector:
    role: ueransim