amf:
  hostname: open5gs-amf-ngap
mcc: '999' # mobile country code 
mnc: '70'   # mobile network code 
name: ueransim-gnb1
nodeSelector: # which node kuberentes the gnb will be deployed 
  role: ueransim
sd: '0x111111' # slicing 
sst: 1 # slicing 
tac: '0001' # tracking area code utilise pour reperer le user equipement a quel gnb est attache 
ues:
  apnList:
  - apn: internet
    emergency: false
    slice:
      sd: '0x111111'
      sst: 1
    type: IPv4
  count: 20
  enabled: true
  initialMSISDN: '0000000001'
  nodeSelector:
    role: ueransim
