- name: Install MicroK8s on Ubuntu
  hosts: all
  become: true

  tasks:
    - name: Ensure apt cache is up to date
      ansible.builtin.apt:
        update_cache: true

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - snapd
        state: present

    - name: Install MicroK8s
      community.general.snap:
        name: microk8s
        classic: true
        state: present

    - name: Add user to microk8s group
      ansible.builtin.user:
        name: "vagrant"
        groups: microk8s
        append: true

    - name: Ensure MicroK8s is running
      ansible.builtin.command: microk8s status --wait-ready
      changed_when: false

    - name: Wait for MicroK8s API to be available
      ansible.builtin.command: microk8s kubectl get nodes
      register: api_check
      retries: 10
      delay: 5
      until: api_check.rc == 0
      changed_when: false

    - name: Copy kubeconfig for user
      ansible.builtin.command: microk8s config
      register: microk8s_config
      changed_when: false

    - name: Ensure ~/.kube directory exists
      ansible.builtin.file:
        path: "/home/vagrant/.kube"
        state: directory
        owner: "vagrant"
        group: "vagrant"
        mode: '0755'

    - name: Save kubeconfig
      ansible.builtin.copy:
        content: "{{ microk8s_config.stdout }}"
        dest: "/home/vagrant/.kube/config"
        owner: "vagrant"
        group: "vagrant"
        mode: '0644'

    - name: Enable MicroK8s addons
      ansible.builtin.shell: microk8s enable dns dashboard storage ingress
      args:
        executable: /bin/bash
      changed_when: false

    - name: Verify MicroK8s addons
      ansible.builtin.command: microk8s status
      changed_when: false

    - name: Add the Open5GS Helm repository
      ansible.builtin.command: microk8s helm repo add adaptivenetlab https://adaptivenetlab.github.io/charts/
      args:
        creates: /var/snap/microk8s/common/helm/repository/adaptivenetlab-index.yaml

    - name: Update Helm repositories
      ansible.builtin.command: microk8s helm repo update
      changed_when: false

    - name: Download Open5GS values file inside the VM
      ansible.builtin.get_url:
        url: "https://gradiant.github.io/5g-charts/docs/open5gs-ueransim-gnb/5gSA-values.yaml"
        dest: "/tmp/5gSA-values.yaml"
        mode: '0644'

    - name: Modify values file inside the VM (Add MongoDB section)
      ansible.builtin.blockinfile:
        path: "/tmp/5gSA-values.yaml"
        block: |
          mongodb:
            livenessProbe:
              initialDelaySeconds: 30
              timeoutSeconds: 30
            readinessProbe:
              initialDelaySeconds: 30
              timeoutSeconds: 30
            startupProbe:
              initialDelaySeconds: 60
              timeoutSeconds: 10

    - name: Install Open5GS using Gradiant Helm chart
      ansible.builtin.command: >
        microk8s helm install open5gs oci://registry-1.docker.io/gradiant/open5gs
        --version 2.2.0
        --namespace open5gs
        --create-namespace
        --values /tmp/5gSA-values.yaml
      changed_when: false

    - name: Wait for Open5GS pods to be ready
      ansible.builtin.command: >
        microk8s kubectl wait --for=condition=Ready pod --all -n open5gs --timeout=300s
      register: result
      until: result.rc == 0
      retries: 10
      delay: 10
      changed_when: false

    - name: Install UERANSIM gNodeB using Gradiant Helm chart
      ansible.builtin.command: >
        microk8s helm install ueransim-gnb oci://registry-1.docker.io/gradiant/ueransim-gnb
        --version 0.2.6
        --namespace open5gs
        --create-namespace
        --values https://gradiant.github.io/5g-charts/docs/open5gs-ueransim-gnb/gnb-ues-values.yaml
      changed_when: false

    - name: Check Open5GS deployment
      ansible.builtin.command: microk8s kubectl get pods -n open5gs
      changed_when: false
