- name: Install MicroK8s on Ubuntu
  hosts: all
  become: true

  tasks:
    - name: Ensure apt cache is up to date
      ansible.builtin.apt:
        update_cache: true

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - snapd
        state: present

    - name: Install MicroK8s
      community.general.snap:
        name: microk8s
        classic: true
        state: present

    - name: Add user to microk8s group
      ansible.builtin.user:
        name: "vagrant"
        groups: microk8s
        append: true

    - name: Ensure MicroK8s is running
      ansible.builtin.command: microk8s status --wait-ready
      changed_when: false

    - name: Wait for MicroK8s API to be available
      ansible.builtin.command: microk8s kubectl get nodes
      register: api_check
      retries: 10
      delay: 5
      until: api_check.rc == 0
      changed_when: false

    - name: Copy kubeconfig for user
      ansible.builtin.command: microk8s config
      register: microk8s_config
      changed_when: false

    - name: Ensure ~/.kube directory exists
      ansible.builtin.file:
        path: "/home/vagrant/.kube"
        state: directory
        owner: "vagrant"
        group: "vagrant"
        mode: "0755"

    - name: Save kubeconfig
      ansible.builtin.copy:
        content: "{{ microk8s_config.stdout }}"
        dest: "/home/vagrant/.kube/config"
        owner: "vagrant"
        group: "vagrant"
        mode: "0644"

    - name: Enable MicroK8s addons
      ansible.builtin.shell: microk8s enable dns dashboard storage ingress
      args:
        executable: /bin/bash
      changed_when: false

    - name: Verify MicroK8s addons
      ansible.builtin.command: microk8s status
      changed_when: false
