---
- name: Join Worker Node to MicroK8s Cluster
  hosts: all
  become: true
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  tasks:
    - name: Ensure apt cache is up to date
      ansible.builtin.apt:
        update_cache: true

    - name: Ensure snapd is installed
      ansible.builtin.apt:
        name: snapd
        state: present
        update_cache: true

    - name: Ensure snapd service is running
      ansible.builtin.systemd:
        name: snapd
        state: started
        enabled: true

    - name: Install MicroK8s
      community.general.snap:
        name: microk8s
        classic: true
        state: present

    - name: Add user to microk8s group
      ansible.builtin.user:
        name: "vagrant"
        groups: microk8s
        append: true

    - name: Ensure MicroK8s is running
      ansible.builtin.command:
        cmd: microk8s status --wait-ready
        creates: /var/snap/microk8s/current/var/lock/cni

    - name: Get Kubernetes Join Command from Master
      ansible.builtin.command:
        cmd: >
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10
          -i /vagrant/.vagrant/machines/master/virtualbox/private_key
          vagrant@{{ master_address }} "microk8s add-node --format short"
      register: join_command
      changed_when: false

    - name: Extract the join command with {{ master_address }}
      ansible.builtin.set_fact:
        join_cmd: "{{ join_command.stdout_lines | select('search', master_address) | first }}"

    - name: Execute Join Command on Worker
      ansible.builtin.command:
        cmd: "{{ join_cmd }}"
      changed_when: false
